### ISSUE TITLE
Upgrading to Laravel 6 and seeing Symphony Errors

### ISSUE THREAD

**Issue by kurucu** [facade/ignition#166]
I upgraded from Laravel 5.8 to Laravel 6 (which does not mention that any special care is required), removed filp/whoops and required facade/ignition, as described in the instructions.

With or without the whoopsHandler, I see only a symphony error page and not an ignition one. If I remove facade/ignition, then the whoops handler comes back.

This is also a Spark application, although I don't think that's relevant.

I believe part of the installation is not described correctly (unless I'm misinterpreting?)

**Comment by mpociot** [comment]
Can you please share what the Symfony error page says?

**Comment by kurucu** [comment]
Hi. The error was `The process has been signaled with signal "9".`

But... I used Laravel Shift to make sure that I hadn't missed anything. I haven't found the change that was hanging over yet (perhaps something missed from a prior upgrade) but it has resolved the issue.

**Comment by am-chris** [comment]
For anyone pulling their hair out about this like I did... I started seeing this error after upgrading to php 7.4 (via brew) on a relatively fresh Laravel Spark project (laravel/framework ^6.2, latest Spark as of Dec 6 2019). I'm using Laravel Valet, the fix was to reinstall Valet by running `valet install`
