### ISSUE TITLE
`flare:test` command question.

### ISSUE THREAD

**Issue by wilburpowery** [facade/ignition#185]
I can't help but feel a little weird by seeing the `flare:test` command in there by default. No other third party package included in the core has any custom commands exposed by default, even more so, there's nothing else connected to a paid service.

Would it be too hard to only show that command is someone has explicitly published the `flare.php` config file?

If I publish this file it's safe to suppose I want to use Flare as my error tracker and having that command would make sense.

**Comment by mpociot** [comment]
We can’t control the command by the existence of the config file, since you can also use Flare without having to publish the config file. 
I feel like it’s kind of the same as with the „Share“ tab on ignition. Nobody forces you to use the feature or use the flare test command. 
I don’t think it is possible to only show commands when a specific environment key is available.
