### ISSUE TITLE
Memory leak on providers registration

### ISSUE THREAD

**Issue by rennokki** [facade/ignition#307]
I came here to maybe start a discussion about a possible memory leak coming from this package.

The discussion is here: https://github.com/laravel/framework/issues/33952

The following comment indicates there is an issue with some of the recorders: https://github.com/laravel/framework/issues/33952#issuecomment-685172161

**Comment by X-Coder264** [comment]
I just took a quick look so I might be wrong but the recorders `reset` method is called only when a worker tries to fetch a job from the queue which means there is no resetting with CLI long running commands so the arrays in question just keep getting bigger.

https://github.com/facade/ignition/blob/2.3.6/src/IgnitionServiceProvider.php#L432-L437

**Comment by rennokki** [comment]
Does it help on calling the `reset()` method continuously?

**Comment by mpskovvang** [comment]
I'm experiencing memory issues as well with queues.

Since day one I've `reporting.report_queries` set to `false`, but apparently this isn't respected since commit 9cc51f6b4e92703c331f1422d6c0ca0438a58206.

```
$this->app->make(QueryRecorder::class)->register();
$this->app->make(LogRecorder::class)->register();
$this->app->make(DumpRecorder::class)->register();
```
https://github.com/facade/ignition/commit/9cc51f6b4e92703c331f1422d6c0ca0438a58206#diff-cb4c5957c9c4ed5216b75f1bb182986fR81-R83

In the `register` method the `QueryRecorder` is only registered if enabled:

https://github.com/facade/ignition/blob/9cc51f6b4e92703c331f1422d6c0ca0438a58206/src/IgnitionServiceProvider.php#L101-L103

**Comment by paras-malhotra** [comment]
I've submitted a PR for this.

**Comment by freekmurze** [comment]
We'll continue the conversation on the PR.

**Comment by rennokki** [comment]
Thanks for the follow-up guys!
