### ISSUE TITLE
remote_sites_path is not working as expected. 

### ISSUE THREAD

**Issue by zgetro** [facade/ignition#314]
Doc Link : https://flareapp.io/docs/ignition-for-laravel/configuration#remote-development-server-support
Reproducing Video: https://www.loom.com/share/ef78c099819948529d0bc8318dae362c

**steps to reproduce** 

- run laravel project in container 
- set up facade/ignition as per document.
- change IGNITION_EDITOR to `vscode` in  config/ignition.php
- change remote_sites_path to `[your project path form host system not on docker]` in  config/ignition.php
- make sure you have "facade/ignition": "^2.0", "php": "^7.2.5", "laravel/framework": "^7.0"

_let me know if you need  more information on bug._ 

PS: Thanks for wonderful tool.

**Comment by plakhin** [comment]
Same issue using Laravel Sail on WSL2

**Comment by freekmurze** [comment]
We'd accept a PR that fixes this.

**Comment by Forsakenrox** [comment]
confirm this, no fix for a half of year.

**Comment by Forsakenrox** [comment]
> We'd accept a PR that fixes this.
if you explain how to run this package on test enviroment in debug mode - you're welcome. Or maybe somewhere guide is exist for this case ?

**Comment by Forsakenrox** [comment]
> We'd accept a PR that fixes this.

if you explain how to run this package on test enviroment in debug mode - you're welcome. Or maybe somewhere guide is exist for this case ?

**Comment by lakuapik** [comment]
Hi, recently i came across same problem and found out that i need to properly setup the `remote_sites_path` and `local_sites_path` configuration.

1. make `remote_sites_path` to point laravel `base_path` folder
2. setting `local_sites_path` to my local project folder

```env
# file .env
IGNITION_REMOTE_SITES_PATH=
IGNITION_LOCAL_SITES_PATH=/home/lakuapik/project/laravel
```

```php
<?php
// file: config/ignition.php
'remote_sites_path' => env('IGNITION_REMOTE_SITES_PATH', base_path()),
'local_sites_path' => env('IGNITION_LOCAL_SITES_PATH', ''),
```

@Forsakenrox could you please try this and confirm if it works?

----

fyi @freekmurze i dont  know how ignition works under the hood, but if i make the `remote_sites_path` null or empty string or put a non-exists directory, the `local_sites_path` doesnt work anymore. i think the `remote_sites_path` should be defaulted to `base_path()` instead of empty string.

**Comment by Forsakenrox** [comment]
@lakuapik , hi mate. Yes, you defenetly right. Im was explore the sources and found the same solution (also it writen in config commentary themeself) and here what i think about this issue - neccesserity to define both paths is defined by design of path replacement inside library. Ignition doesnt know what is actualy root path of the project, by this reason hes need to try find difference between local hardcoded path and remote hardcoded path. So, i think here better way to write some logic to automatic determine what is root path of the project. But your solution is also work.

**Comment by weaversam8** [comment]
Hey folks! I've figured out the correct URL scheme for this for VSCode at least. See microsoft/vscode#108257.

It seems that we'd need to add two more configuration parameters to support this:
* The type of remote (`wsl`, `ssh-remote`, something for containers as well)
* The name of the remote or hostname.

Right now, Flare creates a link like this:
```
vscode://file/${remote_sites_path}/${pwd}/${filename}.php:${line_number}
```

The new format would need to be something like:
```
vscode://vscode-remote/${remote_type}+${remote_name}/${pwd}/${filename}.php:${line_number}
```

**Comment by flashadvocate** [comment]
> ```
> base_path()
> ```

Nice catch. Thanks for mentioning the issue with remote being null

**Comment by flashadvocate** [comment]
> fyi @freekmurze i dont know how ignition works under the hood, but if i make the `remote_sites_path` null or empty string or put a non-exists directory, the `local_sites_path` doesnt work anymore. i think the `remote_sites_path` should be defaulted to `base_path()` instead of empty string.

Nice catch. Thanks for mentioning the issue with remote being null

**Comment by freekmurze** [comment]
@lakuapik Would you mind PRing the solution that work for you to https://github.com/spatie/laravel-ignition?

**Comment by lakuapik** [comment]
here you go @freekmurze https://github.com/spatie/laravel-ignition/pull/7
#cmiiw :D

> @lakuapik Would you mind PRing the solution that work for you to https://github.com/spatie/laravel-ignition?

**Comment by freekmurze** [comment]
Thanks!

**Comment by weaversam8** [comment]
I'm noticing that the issue I mentioned here (about remote site paths being unusable in VSCode) seems to be a tangent - should that be another issue?

**Comment by noplanman** [comment]
Thanks @lakuapik for your fix!

For others coming here with the same problem, the solution from https://github.com/facade/ignition/issues/314#issuecomment-827977211 only partly worked for me.

I had to not define the `IGNITION_REMOTE_SITES_PATH` at all in my `.env` for it to work, as it would otherwise overwrite the `base_path()` config:
```
# file .env
#IGNITION_REMOTE_SITES_PATH= <- do not set this!
IGNITION_LOCAL_SITES_PATH=/home/lakuapik/project/laravel

// file: config/ignition.php
'remote_sites_path' => env('IGNITION_REMOTE_SITES_PATH', base_path()),
'local_sites_path' => env('IGNITION_LOCAL_SITES_PATH', ''),
```
