### ISSUE TITLE
CVE-2021-3129 for facade/ignition 1.16.x (Laravel 6)

### ISSUE THREAD

**Issue by jplana-ubc** [facade/ignition#351]
CVE-2021-3129 has been patched on facade/ignition 2.x, but unfortunately this version dropped compatibility for Laravel 6 since version 2.0.0 https://github.com/facade/ignition/blob/master/CHANGELOG.md#200---2020-02-02

In our case we are using Laravel 6* and facade/ignition 1.16.4 and it looks like CVE-2021-3129 is still exploitable.

I've posted the required changes on the original PR, but haven't received any feedback: https://github.com/facade/ignition/pull/334#issuecomment-769454645

Could we please confirm that the exploit is still unpatched in 1.16.4, and if so commit the changes upstream and create the patched version 1.16.5?

Thank you

*Laravel 6 is Long Term Support until September 2022: https://laravel.com/docs/6.x/releases#support-policy

**Comment by freekmurze** [comment]
Thanks for reporting this.

Could you send a PR to the v1 branch with the necessary fix? 

Keep in mind that for most this problem isn't an issue as it can only be  exploited when solutions are allow to run. By default, that's only allow when APP_DEBUG is `true`. You should never set that env variable to `true` in any environment that is publicly reachable.

**Comment by jplana-ubc** [comment]
Hi @freekmurze 

Thanks for your reply. I understand is a low-risk issue, but accidents may happen.

Please find the PR here: https://github.com/facade/ignition/pull/353

**Comment by jonnott** [comment]
@freekmurze @jplana-ubc Good to see 1.16.14 has now been release, but I can't seem to install it for a Laravel 6.x app due to (doesn't seem to like the fact it's on illuminate/support 6.x)..

```
% composer require facade/ignition 1.16.14
./composer.json has been updated
Running composer update facade/ignition
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires facade/ignition 1.16.14 -> satisfiable by facade/ignition[1.16.14].
    - facade/ignition 1.16.14 requires illuminate/support ^7.0|^8.0 -> found illuminate/support[v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.

**Comment by jplana-ubc** [comment]
@freekmurze I believe something happened with the release numbers.

I can see this PR https://github.com/facade/ignition/pull/353 being included in 1.6.15 but not on any of the new 1.16.x tags.

**Comment by bftanase** [comment]
Hello, 

As previously mentioned in the comments, the jump from 1.16.4 to 1.16.14 is pretty huge. I *think* the tag was done by mistake from master instead of v1. This means that users of 6.x will not be able to update.

The end result is any Laravel developer that's using the 6.x version (which is LTS) is at risk. Yeah, I know it shouldn't reach any public server with debug enabled, but it happens more often than you think.

I believe the only thing that needs to be done is a tag from v1 branch, something like 1.16.15. And maybe notify the laravel devs to update their dependency too.

**Comment by jonnott** [comment]
> I believe the only thing that needs to be done is a tag from v1 branch, something like 1.16.15. And maybe notify the laravel devs to update their dependency too.

@freekmurze @rubenvanassche Would be great to get this resolved asap, so L6.x users can be protected from the vulnerability..

**Comment by jonnott** [comment]
@jplana-ubc @rubenvanassche @freekmurze Are we any closer to getting this tagged correctly as either 1.16.5 or 1.16.15 ?

**Comment by rubenvanassche** [comment]
We've just tagged 1.16.15 from `v1` would this solve the problem?

**Comment by bftanase** [comment]
@rubenvanassche, it looks good on my side. The project updated correctly. Thank you!

But as mentioned previously, Laravel should also update their dependency for 6.x branch, otherwise new users might have some unpleasant surprises fit they accidentally copy a project with debug enabled on a public facing server. Maybe you can get in touch with them.

Cheers!

**Comment by jonnott** [comment]
> @rubenvanassche, it looks good on my side. The project updated correctly. Thank you!
> 
> But as mentioned previously, Laravel should also update their dependency for 6.x branch, otherwise new users might have some unpleasant surprises if they accidentally copy a project with debug enabled on a public facing server. Maybe you can get in touch with them.
> 
> Cheers!

PR'd https://github.com/laravel/laravel/pull/5544
