### ISSUE TITLE
Ignition is slow and has some hitches in an Inertia modal

### ISSUE THREAD

**Issue by rubenvanassche** [facade/ignition#51]
It can still be used but is quite slow.

**Comment by AlexVanderbist** [comment]
@rubenvanassche what browser are you using? Seemed alright for me on Chrome

**Comment by rubenvanassche** [comment]
Safari 😬

**Comment by olssonm** [comment]
Also experiencing some extreme slowness when testing Ignition out. Especially if there are "wrongly" imported namespaces/classes due to for example typos – it can take anywhere between 20 and 60 seconds to receive the response:

<img width="1723" alt="Screenshot 2019-09-25 at 09 43 38" src="https://user-images.githubusercontent.com/907114/65580096-52851100-df79-11e9-9085-bf0ccc669ff8.png">

To replicate this case; just spell wrong on Carbon:

`\Carbob\Carbon::now();`

This is not due to the browser.

This was on a small Laravel 5.8 (v5.8.35) app running on Homestead (v9.0.0) on PHP 7.2.

Most other errors such as syntax errors and the like are comparable to filp/whoops.

**Comment by fridzema** [comment]
In my application it is about 10 times slower than whoops.

Whoops:
![Screenshot 2019-09-27 at 10 34 04](https://user-images.githubusercontent.com/8180660/65754949-6a43cd00-e112-11e9-9eb7-82fca11f9a56.png)

Ignition:
![Screenshot 2019-09-27 at 10 30 42](https://user-images.githubusercontent.com/8180660/65754959-6fa11780-e112-11e9-8c2e-f897ebd8add9.png)

**Comment by mpociot** [comment]
@fridzema which exception is thrown there? Do you have additional solution providers installed?

**Comment by fridzema** [comment]
@mpociot this was a simple `Call to undefined function App\Http\Controllers\viewd()` for testing the error page. 

I tried installing ignition again now without the extra stuff and now it is fast enough.
![Screenshot 2019-09-27 at 11 58 44](https://user-images.githubusercontent.com/8180660/65761095-76358c00-e11e-11e9-8925-2eba15a37042.png)

I had installed:
```
astrotomic/ignition-stackoverflow
facade/ignition-code-editor
facade/ignition-tinker-tab
```

After installing these one by one now i have found the culprit is `astrotomic/ignition-stackoverflow`:
![Screenshot 2019-09-27 at 12 04 53](https://user-images.githubusercontent.com/8180660/65761427-0b388500-e11f-11e9-9828-7c4517030699.png)

Sorry for bothering you with this, case closed for me😅

**Comment by king724** [comment]
I am also seeing super slow errors. ~8 seconds for a Class Not Found

Laravel 6.1 (Chrome and Safari)

<img width="1617" alt="Screen Shot 2019-10-04 at 12 52 24 PM" src="https://user-images.githubusercontent.com/350488/66235852-e788b800-e6a5-11e9-9a32-a47534fe704a.png">

**Comment by king724** [comment]
I found a solution to the problem.

First, publish the Ignition config file and then ignore these two solution providers.

```
'ignored_solution_providers' => [
    Facade\Ignition\SolutionProviders\MissingPackageSolutionProvider::class,
    Facade\Ignition\SolutionProviders\MissingImportSolutionProvider::class,
],
```

Valet went from 3000ms to 300ms by disabling the `MissingPackageSolutionProvider` provider as it does a file_get_contents on up to 16 Packagist API calls (1 for the search and up to 15 package detail calls).

Went from 300ms to 95ms by disabling the `MissingImportSolutionProvider` as it looks like it scans a bunch of files/folders in your vendor directory. So if you have a lot of require packages, this timing goes up.

Finally, publish the flare config.php file and set `'collect_git_information'` to false.

`Class Not Found` errors now report back in 35ms with Valet (80ms with Docker).

**Comment by kevyworks** [comment]
In the context of "Slow" creating laravel from scratch in my case 6.* and testing to throw Exception manually seems to fine, but when I install 15+ packages seems to slow down the rendering. I think this is due to laravel's auto-discovery, so I think some libraries that is not a laravel package should be added to "dont-discover".

**Comment by freekmurze** [comment]
The performance problem is fixed in both v1 and v2 by not using the solution provider that would reach out to Packagist.
